//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sUCO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sUCO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Path ToolTip=&quot;Ator&quot; InputMethod.IsInputMethodEnabled=&quot;True&quot;
        ///	xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///	xmlns:s=&quot;clr-namespace:System;assembly=mscorlib&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///	xmlns:uco=&quot;clr-namespace:sUCO.diagram;assembly=sUCO&quot; xmlns:uco0=&quot;clr-namespace:sUCO.diagram.controls;assembly=sUCO&quot;
        ///	xmlns:uco1=&quot;clr-namespace:sUCO.diagram.connection;assembly=sUCO&quot;&gt;
        ///	&lt;Path.Data&gt;
        ///		&lt;GeometryGroup&gt;
        ///			&lt;GeometryGroup.Children&gt;
        ///				&lt;EllipseGeometry RadiusX=&quot;15&quot; Ra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string actor {
            get {
                return ResourceManager.GetString("actor", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addRaia {
            get {
                object obj = ResourceManager.GetObject("addRaia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addUC {
            get {
                object obj = ResourceManager.GetObject("addUC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Path ToolTip=&quot;Caso de Uso&quot; InputMethod.IsInputMethodEnabled=&quot;True&quot;
        ///	xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///	xmlns:s=&quot;clr-namespace:System;assembly=mscorlib&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///	xmlns:uco=&quot;clr-namespace:sUCO.diagram;assembly=sUCO&quot;&gt;
        ///	&lt;Path.Style&gt;
        ///		&lt;Style TargetType=&quot;Path&quot;&gt;
        ///			&lt;Style.BasedOn&gt;
        ///				&lt;Style TargetType=&quot;Path&quot;&gt;
        ///					&lt;Style.Resources&gt;
        ///						&lt;ResourceDictionary /&gt;
        ///					&lt;/Style.Resources&gt;
        ///					&lt;Setter Property=&quot;Shape.Fill&quot;&gt;
        ///						&lt;Setter. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string casoUso {
            get {
                return ResourceManager.GetString("casoUso", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cenarioAlternativo {
            get {
                object obj = ResourceManager.GetObject("cenarioAlternativo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deleteRaia {
            get {
                object obj = ResourceManager.GetObject("deleteRaia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deleteUC {
            get {
                object obj = ResourceManager.GetObject("deleteUC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap diagrama {
            get {
                object obj = ResourceManager.GetObject("diagrama", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editUC {
            get {
                object obj = ResourceManager.GetObject("editUC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap negado {
            get {
                object obj = ResourceManager.GetObject("negado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap raia {
            get {
                object obj = ResourceManager.GetObject("raia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap relatorio {
            get {
                object obj = ResourceManager.GetObject("relatorio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text {
            get {
                object obj = ResourceManager.GetObject("text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uml_actor {
            get {
                object obj = ResourceManager.GetObject("uml_actor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xml {
            get {
                object obj = ResourceManager.GetObject("xml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
